name: ie-bank-infra

on:
  workflow_dispatch:
  push:
    #tests
      paths-ignore:
        - 'scripts/**'

env:
  #RESOURCE_GROUP_DEV: BCSAI2024-DEVOPS-STUDENTS-A-DEV
  RESOURCE_GROUP_UAT: BCSAI2024-DEVOPS-STUDENTS-A-UAT
  RESOURCE_GROUP_PROD: BCSAI2024-DEVOPS-STUDENTS-A-PROD
  SUBSCRIPTION_ID_DEV: e0b9cada-61bc-4b5a-bd7a-52c606726b3b
  USER_ALIAS: massimoridella

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Lint Bicep code 
      # understands how the code runs and detects errors
    - name: Run Bicep linter
      run: az bicep build --file ./main.bicep

  deploy-uat:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'User Acceptance Testing'

    steps:
      # Checkout code
    - uses: actions/checkout@main
    
      # Debug: Print environment variables
    - name: Debug Environment Variables
      run: |
        echo "=== Environment Variables ==="
        echo "ENV: ${{ vars.ENV }}"
        echo "DBHOST: ${{ vars.DBHOST }}"
        echo "DBNAME: ${{ vars.DBNAME }}"
        echo "FLASK_APP: ${{ vars.FLASK_APP }}"
        echo "FLASK_DEBUG: ${{ vars.FLASK_DEBUG }}"
        echo "USER_ALIAS: ${{ env.USER_ALIAS }}"
        echo "RESOURCE_GROUP_UAT: ${{ env.RESOURCE_GROUP_UAT }}"
        echo "SUBSCRIPTION_ID_DEV: ${{ env.SUBSCRIPTION_ID_DEV }}"
        echo "=== End Environment Variables ==="
    
      # Log into Azure
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file test
    - name: deploy
      uses: azure/arm-deploy@v2
      with:
        subscriptionId: ${{ env.SUBSCRIPTION_ID_DEV }}
        resourceGroupName: ${{ env.RESOURCE_GROUP_UAT }}
        template: ./main.bicep
        parameters: ./parameters/uat.parameters.json userAlias=${{ env.USER_ALIAS }} appServiceAPIEnvVarENV=${{ vars.ENV }} appServiceAPIEnvVarDBHOST=${{ vars.DBHOST }} appServiceAPIEnvVarDBNAME=${{ vars.DBNAME }} appServiceAPIEnvVarDBPASS=${{ secrets.DBPASS }} appServiceAPIDBHostDBUSER=${{ secrets.DBUSER }} appServiceAPIDBHostFLASK_APP=${{ vars.FLASK_APP }} appServiceAPIDBHostFLASK_DEBUG=${{ vars.FLASK_DEBUG }}
        deploymentName: ${{ env.USER_ALIAS }}
  
  deploy-prod:
      runs-on: ubuntu-latest
      needs: build
      environment:
        name: 'Production'

      steps:
        # Checkout code
      - uses: actions/checkout@main
      
        # Debug: Print environment variables
      - name: Debug Environment Variables
        run: |
          echo "=== Environment Variables ==="
          echo "ENV: ${{ vars.ENV }}"
          echo "DBHOST: ${{ vars.DBHOST }}"
          echo "DBNAME: ${{ vars.DBNAME }}"
          echo "FLASK_APP: ${{ vars.FLASK_APP }}"
          echo "FLASK_DEBUG: ${{ vars.FLASK_DEBUG }}"
          echo "USER_ALIAS: ${{ env.USER_ALIAS }}"
          echo "RESOURCE_GROUP_PROD: ${{ env.RESOURCE_GROUP_PROD }}"
          echo "SUBSCRIPTION_ID_DEV: ${{ env.SUBSCRIPTION_ID_DEV }}"
          echo "=== End Environment Variables ==="
      
        # Log into Azure
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

        # Deploy Bicep file test
      - name: deploy
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ env.SUBSCRIPTION_ID_DEV }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_PROD }}
          template: ./main.bicep
          parameters: ./parameters/prod.parameters.json userAlias=${{ env.USER_ALIAS }} appServiceAPIEnvVarENV=${{ vars.ENV }} appServiceAPIEnvVarDBHOST=${{ vars.DBHOST }} appServiceAPIEnvVarDBNAME=${{ vars.DBNAME }} appServiceAPIEnvVarDBPASS=${{ secrets.DBPASS }} appServiceAPIDBHostDBUSER=${{ secrets.DBUSER }} appServiceAPIDBHostFLASK_APP=${{ vars.FLASK_APP }} appServiceAPIDBHostFLASK_DEBUG=${{ vars.FLASK_DEBUG }}
          deploymentName: ${{ env.USER_ALIAS }} 